version: '3.8'
services:
  inventario-service:
    build: ./inventario-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - productos-service

  productos-service:
    build: ./productos-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod