version: "3.8"

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - sqlserver_data:/var/opt/mssql
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 90 && 
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'CREATE DATABASE inventario_db' &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'CREATE DATABASE productos_db' &&
        wait
      "
    networks:
      - backend_network

  inventario-service:
    build: ./inventario-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=inventario_db;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong!Passw0rd
      - PRODUCTOS_API_KEY=2f8e1b9c-4a7d-4c2b-9e3a-123456789abc
    depends_on:
      sqlserver:
        condition: service_healthy
      productos-service:
        condition: service_started
    restart: unless-stopped
    networks:
      - backend_network

  productos-service:
    build: ./productos-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=productos_db;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong!Passw0rd
      - API_KEY=2f8e1b9c-4a7d-4c2b-9e3a-123456789abc
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend_network

volumes:
  sqlserver_data:

networks:
  backend_network:
    driver: bridge
